-- SightEnhance
-- Author: ApprenTice
-- DateCreated: 3/5/2026 10:55:02 PM
--------------------------------------------------------------
INSERT INTO Types (Type, Kind) VALUES
('ABILITY_HUMAN_PLAYER_UNIT_SIGHT_ENHANCE', 'KIND_ABILITY');

INSERT INTO TypeTags (Type, Tag) VALUES
('ABILITY_HUMAN_PLAYER_UNIT_SIGHT_ENHANCE', 'CLASS_ALL_UNITS');

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_MAJOR_CIV', 'HUMAN_PLAYER_UNIT_SIGHT_ENHANCE_GRANT_ABILITY');

INSERT INTO UnitAbilities (UnitAbilityType, Name, Description, Inactive) VALUES
('ABILITY_HUMAN_PLAYER_UNIT_SIGHT_ENHANCE', NULL, NULL, 1);

INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES
('ABILITY_HUMAN_PLAYER_UNIT_SIGHT_ENHANCE', 'HUMAN_PLAYER_UNIT_SIGHT_ENHANCE');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('HUMAN_PLAYER_UNIT_SIGHT_ENHANCE_GRANT_ABILITY', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', 0, 0, 0, 'HUMAN_PLAYER_SIGHT_ENHANCE_REQUIREMENT_SET', NULL),
('HUMAN_PLAYER_UNIT_SIGHT_ENHANCE', 'MODIFIER_PLAYER_UNIT_ADJUST_SIGHT', 0, 0, 0, NULL, NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('HUMAN_PLAYER_UNIT_SIGHT_ENHANCE_GRANT_ABILITY', 'AbilityType', 'ABILITY_HUMAN_PLAYER_UNIT_SIGHT_ENHANCE'),
('HUMAN_PLAYER_UNIT_SIGHT_ENHANCE', 'Amount', '1');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('HUMAN_PLAYER_SIGHT_ENHANCE_REQUIREMENT_SET', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('HUMAN_PLAYER_SIGHT_ENHANCE_REQUIREMENT_SET', 'PLAYER_IS_HUMAN');

INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('PLAYER_IS_HUMAN', 'REQUIREMENT_PLAYER_IS_HUMAN');