#!/usr/bin/env python3
"""Generate the deterministic SQL data used by People's War."""

from __future__ import annotations

from pathlib import Path


COMBAT_MAX = 100
CITY_POPULATION_THRESHOLDS = tuple(range(1, 92, 10))
ROOT = Path(__file__).resolve().parents[1]
GAMEPLAY = ROOT / "Gameplay"


def sql_values(rows: list[tuple[object, ...]]) -> str:
    def quote(value: object) -> str:
        if value is None:
            return "NULL"
        if isinstance(value, (int, float)):
            return str(value)
        return "'" + str(value).replace("'", "''") + "'"

    return ",\n".join("  (" + ", ".join(quote(value) for value in row) + ")" for row in rows)


def statement(table: str, columns: tuple[str, ...], rows: list[tuple[object, ...]]) -> str:
    return f"INSERT INTO {table} ({', '.join(columns)}) VALUES\n{sql_values(rows)};\n"


def generate_abilities() -> str:
    types: list[tuple[object, ...]] = []
    abilities: list[tuple[object, ...]] = []
    tags: list[tuple[object, ...]] = []
    ability_modifiers: list[tuple[object, ...]] = []
    modifiers: list[tuple[object, ...]] = []
    arguments: list[tuple[object, ...]] = []
    strings: list[tuple[object, ...]] = []

    # Lua assigns exactly one generated combat or religious ability from total population.
    for level in range(1, COMBAT_MAX + 1):
        preview_tag = f"LOC_PEOPLES_WAR_PREVIEW_{level}"
        for category, tag in (
            ("COMBAT", "CLASS_ALL_COMBAT_UNITS"),
            ("RELIGIOUS", "CLASS_RELIGIOUS_ALL"),
        ):
            ability = f"ABILITY_PEOPLES_WAR_{category}_{level}"
            modifier = f"PEOPLES_WAR_{category}_STRENGTH_{level}"
            types.append((ability, "KIND_ABILITY"))
            abilities.append((ability, 1))
            tags.append((ability, tag))
            ability_modifiers.append((ability, modifier))
            modifiers.append((modifier, "MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH"))
            arguments.append((modifier, "Amount", level))
            strings.append((modifier, "Preview", preview_tag))

    modifiers.append(
        (
            "PEOPLES_WAR_NO_POPULATION_LOSS_AFTER_CONQUEST",
            "MODIFIER_PLAYER_ADJUST_POPULATION_AFTER_CONQUEST",
        )
    )
    arguments.append(
        ("PEOPLES_WAR_NO_POPULATION_LOSS_AFTER_CONQUEST", "Percent", 100)
    )

    sections = [
        "-- Generated by Tools/generate_peoples_war_abilities.py. Do not edit by hand.\n",
        statement("Types", ("Type", "Kind"), types),
        statement("UnitAbilities", ("UnitAbilityType", "Inactive"), abilities),
        statement("TypeTags", ("Type", "Tag"), tags),
        statement(
            "UnitAbilityModifiers", ("UnitAbilityType", "ModifierId"), ability_modifiers
        ),
        statement("Modifiers", ("ModifierId", "ModifierType"), modifiers),
        statement("ModifierArguments", ("ModifierId", "Name", "Value"), arguments),
        statement("ModifierStrings", ("ModifierId", "Context", "Text"), strings),
    ]
    return "\n".join(sections)


def generate_city_effects() -> str:
    modifiers: list[tuple[object, ...]] = []
    modifier_arguments: list[tuple[object, ...]] = []
    requirement_sets: list[tuple[object, ...]] = []
    set_requirements: list[tuple[object, ...]] = []
    requirements: list[tuple[object, ...]] = []
    requirement_arguments: list[tuple[object, ...]] = []

    # These per-city threshold modifiers stack to implement ceil(population / 10).
    for threshold in CITY_POPULATION_THRESHOLDS:
        suffix = f"{threshold:03d}"
        requirement_set = f"PEOPLES_WAR_CITY_POP_AT_LEAST_{suffix}"
        requirement = f"REQUIRES_PEOPLES_WAR_CITY_POP_AT_LEAST_{suffix}"

        requirement_sets.append((requirement_set, "REQUIREMENTSET_TEST_ALL"))
        set_requirements.append((requirement_set, requirement))
        requirements.append((requirement, "REQUIREMENT_CITY_HAS_X_POPULATION"))
        requirement_arguments.append((requirement, "Amount", threshold))

        for modifier, modifier_type in (
            (
                f"PEOPLES_WAR_CITY_RANGED_POP_{suffix}",
                "MODIFIER_PLAYER_CITIES_ADJUST_RANGED_STRIKE",
            ),
            (
                f"PEOPLES_WAR_CITY_DEFENSE_POP_{suffix}",
                "MODIFIER_PLAYER_CITIES_ADJUST_OUTER_DEFENSE",
            ),
            (
                f"PEOPLES_WAR_CITY_SPY_DEFENSE_POP_{suffix}",
                "MODIFIER_PEOPLES_WAR_PLAYER_CITIES_ADJUST_SPY_BONUS",
            ),
        ):
            modifiers.append((modifier, modifier_type, requirement_set))
            modifier_arguments.append((modifier, "Amount", 1))

    # Per-population yield modifiers are recalculated automatically by the database layer.
    for yield_name, amount in (
        ("GOLD", 2),
        ("PRODUCTION", 0.5),
        ("FAITH", 1),
        ("SCIENCE", 0.5),
        ("CULTURE", 0.5),
    ):
        modifier = f"PEOPLES_WAR_CITY_POPULATION_{yield_name}"
        modifiers.append(
            (
                modifier,
                "MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION",
                None,
            )
        )
        modifier_arguments.extend(
            (
                (modifier, "YieldType", f"YIELD_{yield_name}"),
                (modifier, "Amount", amount),
            )
        )

    sections = [
        "-- Generated by Tools/generate_peoples_war_abilities.py. Do not edit by hand.\n",
        "INSERT INTO Types (Type, Kind) VALUES\n"
        "  ('MODIFIER_PEOPLES_WAR_PLAYER_CITIES_ADJUST_SPY_BONUS', 'KIND_MODIFIER');\n",
        "INSERT INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES\n"
        "  ('MODIFIER_PEOPLES_WAR_PLAYER_CITIES_ADJUST_SPY_BONUS', "
        "'COLLECTION_PLAYER_CITIES', 'EFFECT_ADJUST_CITY_SPY_BONUS');\n",
        statement(
            "Modifiers",
            ("ModifierId", "ModifierType", "SubjectRequirementSetId"),
            modifiers,
        ),
        statement(
            "ModifierArguments", ("ModifierId", "Name", "Value"), modifier_arguments
        ),
        statement(
            "RequirementSets", ("RequirementSetId", "RequirementSetType"), requirement_sets
        ),
        statement(
            "RequirementSetRequirements",
            ("RequirementSetId", "RequirementId"),
            set_requirements,
        ),
        statement(
            "Requirements", ("RequirementId", "RequirementType"), requirements
        ),
        statement(
            "RequirementArguments",
            ("RequirementId", "Name", "Value"),
            requirement_arguments,
        ),
    ]
    return "\n".join(sections)


def generate_localization() -> str:
    rows: list[tuple[object, ...]] = [
        ("zh_Hans_CN", "LOC_PEOPLES_WAR_DISSOLVE_BUTTON", "解放"),
        ("en_US", "LOC_PEOPLES_WAR_DISSOLVE_BUTTON", "Dissolve"),
        (
            "zh_Hans_CN",
            "LOC_PEOPLES_WAR_DISSOLVE_DESCRIPTION",
            "撤销该城市的城市建制，并将全部人口重新分配至帝国其他已确定保留的城市。无法均分的余数依次分配给其中人口最少的城市，每座城市一个人口。",
        ),
        (
            "en_US",
            "LOC_PEOPLES_WAR_DISSOLVE_DESCRIPTION",
            "Dissolve this city and redistribute its entire population among your other retained cities. Any remainder is assigned one population each to the least-populous eligible cities.",
        ),
        (
            "zh_Hans_CN",
            "LOC_PEOPLES_WAR_DISSOLVE_NO_RECIPIENTS",
            "没有其他已确定保留的城市可以接收人口。",
        ),
        (
            "en_US",
            "LOC_PEOPLES_WAR_DISSOLVE_NO_RECIPIENTS",
            "No other retained city can receive this population.",
        ),
        (
            "zh_Hans_CN",
            "LOC_PEOPLES_WAR_DISSOLVE_COMMAND_BLOCKED",
            "当前游戏状态不允许解放该城市。",
        ),
        (
            "en_US",
            "LOC_PEOPLES_WAR_DISSOLVE_COMMAND_BLOCKED",
            "The current game state does not allow this city to be dissolved.",
        ),
    ]

    for level in range(1, COMBAT_MAX + 1):
        tag = f"LOC_PEOPLES_WAR_PREVIEW_{level}"
        rows.append(("zh_Hans_CN", tag, f"人民战争+{level}"))
        rows.append(("en_US", tag, f"People's War +{level}"))

    return (
        "-- Generated by Tools/generate_peoples_war_abilities.py. Do not edit by hand.\n\n"
        + statement("LocalizedText", ("Language", "Tag", "Text"), rows).replace(
            "INSERT INTO LocalizedText", "INSERT OR REPLACE INTO LocalizedText", 1
        )
    )


def write_utf8_lf(path: Path, content: str) -> None:
    path.write_text(content.rstrip() + "\n", encoding="utf-8", newline="\n")


def main() -> None:
    GAMEPLAY.mkdir(parents=True, exist_ok=True)
    write_utf8_lf(GAMEPLAY / "PeoplesWar_Abilities.sql", generate_abilities())
    write_utf8_lf(GAMEPLAY / "PeoplesWar_CityEffects.sql", generate_city_effects())
    write_utf8_lf(GAMEPLAY / "PeoplesWar_Localization.sql", generate_localization())


if __name__ == "__main__":
    main()
