#!/usr/bin/env python3
"""Generate the deterministic SQL data used by People's War."""

from __future__ import annotations

from pathlib import Path


COMBAT_MAX = 100
CITY_POPULATION_EFFECT_STEP = 5
CITY_POPULATION_THRESHOLDS = tuple(range(1, 97, CITY_POPULATION_EFFECT_STEP))
RANGED_STRIKE_PER_TIER = 2
DEFENSE_PER_TIER = 2
SPY_LEVEL_PER_TIER = 1
ROOT = Path(__file__).resolve().parents[1]
GAMEPLAY = ROOT / "Gameplay"


def sql_values(rows: list[tuple[object, ...]]) -> str:
    def quote(value: object) -> str:
        if value is None:
            return "NULL"
        if isinstance(value, (int, float)):
            return str(value)
        return "'" + str(value).replace("'", "''") + "'"

    return ",\n".join("  (" + ", ".join(quote(value) for value in row) + ")" for row in rows)


def statement(table: str, columns: tuple[str, ...], rows: list[tuple[object, ...]]) -> str:
    return f"INSERT INTO {table} ({', '.join(columns)}) VALUES\n{sql_values(rows)};\n"


def generate_abilities() -> str:
    types: list[tuple[object, ...]] = []
    abilities: list[tuple[object, ...]] = []
    tags: list[tuple[object, ...]] = []
    ability_modifiers: list[tuple[object, ...]] = []
    modifiers: list[tuple[object, ...]] = []
    arguments: list[tuple[object, ...]] = []
    strings: list[tuple[object, ...]] = []

    # Lua assigns exactly one generated combat or religious ability from total population.
    for level in range(1, COMBAT_MAX + 1):
        preview_tag = f"LOC_PEOPLES_WAR_PREVIEW_{level}"
        for category, tag in (
            ("COMBAT", "CLASS_ALL_COMBAT_UNITS"),
            ("RELIGIOUS", "CLASS_RELIGIOUS_ALL"),
        ):
            ability = f"ABILITY_PEOPLES_WAR_{category}_{level}"
            modifier = f"PEOPLES_WAR_{category}_STRENGTH_{level}"
            types.append((ability, "KIND_ABILITY"))
            abilities.append((ability, 1))
            tags.append((ability, tag))
            ability_modifiers.append((ability, modifier))
            modifiers.append((modifier, "MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH"))
            arguments.append((modifier, "Amount", level))
            strings.append((modifier, "Preview", preview_tag))

    modifiers.append(
        (
            "PEOPLES_WAR_NO_POPULATION_LOSS_AFTER_CONQUEST",
            "MODIFIER_PLAYER_ADJUST_POPULATION_AFTER_CONQUEST",
        )
    )
    arguments.append(
        ("PEOPLES_WAR_NO_POPULATION_LOSS_AFTER_CONQUEST", "Percent", 100)
    )

    sections = [
        "-- Generated by Tools/generate_peoples_war_abilities.py. Do not edit by hand.\n",
        statement("Types", ("Type", "Kind"), types),
        statement("UnitAbilities", ("UnitAbilityType", "Inactive"), abilities),
        statement("TypeTags", ("Type", "Tag"), tags),
        statement(
            "UnitAbilityModifiers", ("UnitAbilityType", "ModifierId"), ability_modifiers
        ),
        statement("Modifiers", ("ModifierId", "ModifierType"), modifiers),
        statement("ModifierArguments", ("ModifierId", "Name", "Value"), arguments),
        statement("ModifierStrings", ("ModifierId", "Context", "Text"), strings),
    ]
    return "\n".join(sections)


def generate_city_effects() -> str:
    modifiers: list[tuple[object, ...]] = []
    modifier_arguments: list[tuple[object, ...]] = []
    requirement_sets: list[tuple[object, ...]] = []
    set_requirements: list[tuple[object, ...]] = []
    requirements: list[tuple[object, ...]] = []
    requirement_arguments: list[tuple[object, ...]] = []

    # These per-city threshold modifiers stack: one tier per 5 population, each
    # granting +2 ranged strike, +2 outer defense and +1 counter-spy level.
    for threshold in CITY_POPULATION_THRESHOLDS:
        suffix = f"{threshold:03d}"
        requirement_set = f"PEOPLES_WAR_CITY_POP_AT_LEAST_{suffix}"
        requirement = f"REQUIRES_PEOPLES_WAR_CITY_POP_AT_LEAST_{suffix}"

        requirement_sets.append((requirement_set, "REQUIREMENTSET_TEST_ALL"))
        set_requirements.append((requirement_set, requirement))
        requirements.append((requirement, "REQUIREMENT_CITY_HAS_X_POPULATION"))
        requirement_arguments.append((requirement, "Amount", threshold))

        for modifier, modifier_type, amount in (
            (
                f"PEOPLES_WAR_CITY_RANGED_POP_{suffix}",
                "MODIFIER_PLAYER_CITIES_ADJUST_RANGED_STRIKE",
                RANGED_STRIKE_PER_TIER,
            ),
            (
                f"PEOPLES_WAR_CITY_DEFENSE_POP_{suffix}",
                "MODIFIER_PLAYER_CITIES_ADJUST_OUTER_DEFENSE",
                DEFENSE_PER_TIER,
            ),
            (
                f"PEOPLES_WAR_CITY_SPY_DEFENSE_POP_{suffix}",
                "MODIFIER_PEOPLES_WAR_PLAYER_CITIES_ADJUST_SPY_BONUS",
                SPY_LEVEL_PER_TIER,
            ),
        ):
            modifiers.append((modifier, modifier_type, requirement_set))
            modifier_arguments.append((modifier, "Amount", amount))

    sections = [
        "-- Generated by Tools/generate_peoples_war_abilities.py. Do not edit by hand.\n",
        "INSERT INTO Types (Type, Kind) VALUES\n"
        "  ('MODIFIER_PEOPLES_WAR_PLAYER_CITIES_ADJUST_SPY_BONUS', 'KIND_MODIFIER');\n",
        "INSERT INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES\n"
        "  ('MODIFIER_PEOPLES_WAR_PLAYER_CITIES_ADJUST_SPY_BONUS', "
        "'COLLECTION_PLAYER_CITIES', 'EFFECT_ADJUST_CITY_SPY_BONUS');\n",
        statement(
            "Modifiers",
            ("ModifierId", "ModifierType", "SubjectRequirementSetId"),
            modifiers,
        ),
        statement(
            "ModifierArguments", ("ModifierId", "Name", "Value"), modifier_arguments
        ),
        statement(
            "RequirementSets", ("RequirementSetId", "RequirementSetType"), requirement_sets
        ),
        statement(
            "RequirementSetRequirements",
            ("RequirementSetId", "RequirementId"),
            set_requirements,
        ),
        statement(
            "Requirements", ("RequirementId", "RequirementType"), requirements
        ),
        statement(
            "RequirementArguments",
            ("RequirementId", "Name", "Value"),
            requirement_arguments,
        ),
    ]
    return "\n".join(sections)


def generate_localization() -> str:
    # The Dividing Grace strings now live in that mod's draft; People's War only keeps ability previews.
    rows: list[tuple[object, ...]] = []

    for level in range(1, COMBAT_MAX + 1):
        tag = f"LOC_PEOPLES_WAR_PREVIEW_{level}"
        rows.append(("zh_Hans_CN", tag, f"人民战争+{level}"))
        rows.append(("en_US", tag, f"People's War +{level}"))

    return (
        "-- Generated by Tools/generate_peoples_war_abilities.py. Do not edit by hand.\n\n"
        + statement("LocalizedText", ("Language", "Tag", "Text"), rows).replace(
            "INSERT INTO LocalizedText", "INSERT OR REPLACE INTO LocalizedText", 1
        )
    )


def write_utf8_lf(path: Path, content: str) -> None:
    path.write_text(content.rstrip() + "\n", encoding="utf-8", newline="\n")


def main() -> None:
    GAMEPLAY.mkdir(parents=True, exist_ok=True)
    write_utf8_lf(GAMEPLAY / "PeoplesWar_Abilities.sql", generate_abilities())
    write_utf8_lf(GAMEPLAY / "PeoplesWar_CityEffects.sql", generate_city_effects())
    write_utf8_lf(GAMEPLAY / "PeoplesWar_Localization.sql", generate_localization())


if __name__ == "__main__":
    main()
