INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
  ('TRAIT_LEADER_MAJOR_CIV', 'POPULATION_YIELDS_GOLD'),
  ('TRAIT_LEADER_MAJOR_CIV', 'POPULATION_YIELDS_PRODUCTION'),
  ('TRAIT_LEADER_MAJOR_CIV', 'POPULATION_YIELDS_FAITH'),
  ('TRAIT_LEADER_MAJOR_CIV', 'POPULATION_YIELDS_SCIENCE'),
  ('TRAIT_LEADER_MAJOR_CIV', 'POPULATION_YIELDS_CULTURE');

INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) VALUES
  ('POPULATION_YIELDS_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION', 'PLAYER_IS_HUMAN'),
  ('POPULATION_YIELDS_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION', 'PLAYER_IS_HUMAN'),
  ('POPULATION_YIELDS_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION', 'PLAYER_IS_HUMAN'),
  ('POPULATION_YIELDS_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION', 'PLAYER_IS_HUMAN'),
  ('POPULATION_YIELDS_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION', 'PLAYER_IS_HUMAN');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
  ('POPULATION_YIELDS_GOLD', 'YieldType', 'YIELD_GOLD'),
  ('POPULATION_YIELDS_GOLD', 'Amount', 2),
  ('POPULATION_YIELDS_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
  ('POPULATION_YIELDS_PRODUCTION', 'Amount', 0.5),
  ('POPULATION_YIELDS_FAITH', 'YieldType', 'YIELD_FAITH'),
  ('POPULATION_YIELDS_FAITH', 'Amount', 1),
  ('POPULATION_YIELDS_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
  ('POPULATION_YIELDS_SCIENCE', 'Amount', 0.5),
  ('POPULATION_YIELDS_CULTURE', 'YieldType', 'YIELD_CULTURE'),
  ('POPULATION_YIELDS_CULTURE', 'Amount', 0.5);
