-- Great Synthesizer compatibility patches for confirmed leader-specific requirements.

INSERT INTO Requirements (RequirementId, RequirementType)
SELECT 'GSYN_REQUIRES_PLAYER_HAS_TRAIT_LEADER_LINCOLN', 'REQUIREMENT_PLAYER_HAS_CIVILIZATION_OR_LEADER_TRAIT'
WHERE NOT EXISTS
(
  SELECT 1 FROM Requirements
  WHERE RequirementId = 'GSYN_REQUIRES_PLAYER_HAS_TRAIT_LEADER_LINCOLN'
);

INSERT INTO RequirementArguments (RequirementId, Name, Value)
SELECT 'GSYN_REQUIRES_PLAYER_HAS_TRAIT_LEADER_LINCOLN', 'TraitType', 'TRAIT_LEADER_LINCOLN'
WHERE NOT EXISTS
(
  SELECT 1 FROM RequirementArguments
  WHERE RequirementId = 'GSYN_REQUIRES_PLAYER_HAS_TRAIT_LEADER_LINCOLN'
    AND Name = 'TraitType'
);

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
SELECT 'GSYN_PLAYER_HAS_TRAIT_LEADER_LINCOLN', 'REQUIREMENTSET_TEST_ALL'
WHERE NOT EXISTS
(
  SELECT 1 FROM RequirementSets
  WHERE RequirementSetId = 'GSYN_PLAYER_HAS_TRAIT_LEADER_LINCOLN'
);

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT 'GSYN_PLAYER_HAS_TRAIT_LEADER_LINCOLN', 'GSYN_REQUIRES_PLAYER_HAS_TRAIT_LEADER_LINCOLN'
WHERE NOT EXISTS
(
  SELECT 1 FROM RequirementSetRequirements
  WHERE RequirementSetId = 'GSYN_PLAYER_HAS_TRAIT_LEADER_LINCOLN'
    AND RequirementId = 'GSYN_REQUIRES_PLAYER_HAS_TRAIT_LEADER_LINCOLN'
);

UPDATE Modifiers
SET SubjectRequirementSetId = 'GSYN_PLAYER_HAS_TRAIT_LEADER_LINCOLN'
WHERE ModifierId = 'PLANTATION_NEGATIVE_LOYALTY'
  AND SubjectRequirementSetId = 'REQUIRES_PLAYER_IS_LINCOLN';

INSERT INTO Requirements (RequirementId, RequirementType)
SELECT 'GSYN_PLAYER_HAS_TRAIT_LEADER_HARALD_ALT', 'REQUIREMENT_PLAYER_HAS_CIVILIZATION_OR_LEADER_TRAIT'
WHERE NOT EXISTS
(
  SELECT 1 FROM Requirements
  WHERE RequirementId = 'GSYN_PLAYER_HAS_TRAIT_LEADER_HARALD_ALT'
);

INSERT INTO RequirementArguments (RequirementId, Name, Value)
SELECT 'GSYN_PLAYER_HAS_TRAIT_LEADER_HARALD_ALT', 'TraitType', 'TRAIT_LEADER_HARALD_ALT'
WHERE NOT EXISTS
(
  SELECT 1 FROM RequirementArguments
  WHERE RequirementId = 'GSYN_PLAYER_HAS_TRAIT_LEADER_HARALD_ALT'
    AND Name = 'TraitType'
);

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
SELECT 'GSYN_PLAYER_HAS_TRAIT_LEADER_HARALD_ALT', 'REQUIREMENTSET_TEST_ALL'
WHERE NOT EXISTS
(
  SELECT 1 FROM RequirementSets
  WHERE RequirementSetId = 'GSYN_PLAYER_HAS_TRAIT_LEADER_HARALD_ALT'
);

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT 'GSYN_PLAYER_HAS_TRAIT_LEADER_HARALD_ALT', 'GSYN_PLAYER_HAS_TRAIT_LEADER_HARALD_ALT'
WHERE NOT EXISTS
(
  SELECT 1 FROM RequirementSetRequirements
  WHERE RequirementSetId = 'GSYN_PLAYER_HAS_TRAIT_LEADER_HARALD_ALT'
    AND RequirementId = 'GSYN_PLAYER_HAS_TRAIT_LEADER_HARALD_ALT'
);

UPDATE Modifiers
SET SubjectRequirementSetId = 'GSYN_PLAYER_HAS_TRAIT_LEADER_HARALD_ALT'
WHERE ModifierId = 'STAVE_CHURCH_INFLUENCEPOINTS'
  AND SubjectRequirementSetId = 'PLAYER_IS_HARALD_ALT';
