-- AdditionalPolicyCardSlots
-- Author: ApprenTice
-- DateCreated: 3/1/2026 11:22:40 PM
--------------------------------------------------------------
INSERT INTO CivicModifiers (CivicType, ModifierId) VALUES 
('CIVIC_MILITARY_TRADITION', 'MILITARY_TRADITION_ADDITIONAL_MILITARY_POLICY_SLOT'),
('CIVIC_FOREIGN_TRADE', 'FOREIGN_TRADE_ADDITIONAL_ECONOMIC_POLICY_SLOT'),
('CIVIC_POLITICAL_PHILOSOPHY', 'POLITICAL_PHILOSOPHY_ADDITIONAL_DIPLOMATIC_POLICY_SLOT'),
('CIVIC_MYSTICISM', 'MYSTICISM_ADDITIONAL_WILDCARD_POLICY_SLOT');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('MILITARY_TRADITION_ADDITIONAL_MILITARY_POLICY_SLOT', 'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER', 0, 0, 0, NULL, 'HUMAN_PLAYER_ADDITIONAL_POLICY_CARD_SLOTS_REQUIREMENT_SET'),
('FOREIGN_TRADE_ADDITIONAL_ECONOMIC_POLICY_SLOT', 'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER', 0, 0, 0, NULL, 'HUMAN_PLAYER_ADDITIONAL_POLICY_CARD_SLOTS_REQUIREMENT_SET'),
('POLITICAL_PHILOSOPHY_ADDITIONAL_DIPLOMATIC_POLICY_SLOT', 'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER', 0, 0, 0, NULL, 'HUMAN_PLAYER_ADDITIONAL_POLICY_CARD_SLOTS_REQUIREMENT_SET'),
('MYSTICISM_ADDITIONAL_WILDCARD_POLICY_SLOT', 'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER', 0, 0, 0, NULL, 'HUMAN_PLAYER_ADDITIONAL_POLICY_CARD_SLOTS_REQUIREMENT_SET');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('MILITARY_TRADITION_ADDITIONAL_MILITARY_POLICY_SLOT','GovernmentSlotType','SLOT_MILITARY'),
('FOREIGN_TRADE_ADDITIONAL_ECONOMIC_POLICY_SLOT','GovernmentSlotType','SLOT_ECONOMIC'),
('POLITICAL_PHILOSOPHY_ADDITIONAL_DIPLOMATIC_POLICY_SLOT','GovernmentSlotType','SLOT_DIPLOMATIC'),
('MYSTICISM_ADDITIONAL_WILDCARD_POLICY_SLOT','GovernmentSlotType','SLOT_WILDCARD');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('HUMAN_PLAYER_ADDITIONAL_POLICY_CARD_SLOTS_REQUIREMENT_SET', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('HUMAN_PLAYER_ADDITIONAL_POLICY_CARD_SLOTS_REQUIREMENT_SET', 'PLAYER_IS_HUMAN');

INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('PLAYER_IS_HUMAN', 'REQUIREMENT_PLAYER_IS_HUMAN');